- name: Azure (azshell)
  hosts: 127.0.0.1
  connection: local

  vars:
    azshell_filename: "{{ 'azshell_macOS_64-bit.tar.gz' if ansible_distribution == 'MacOSX' else 'azshell_linux_64-bit.tar.gz' }}"
    azshell_version: v0.2.2

  tasks:
    - name: Create azshell folder
      file:
        path: ~/.azshell
        state: directory

    - name: Download azshell
      unarchive:
        src: https://github.com/yangl900/azshell/releases/download/{{ azshell_version }}/{{ azshell_filename }}
        dest: ~/.azshell
        remote_src: yes
        creates: ~/.azshell/azshell

    - name: Create shortcut to azshell
      file:
        path: ~/bin/azshell
        src: ~/.azshell/azshell
        state: link
