- name: VLC
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Install VLC (Linux)
      become: yes
      apt:
        package: vlc
      when: not is_mac and not is_wsl

    # macOS

    - name: Install VLC (macOS)
      homebrew_cask:
        name: vlc
      when: is_mac
