- name: Broot
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # Linux

    - name: Install broot (Linux)
      become: yes
      get_url:
        url: https://dystroy.org/broot/download/x86_64-linux/broot
        dest: /usr/local/bin/broot
        mode: 0755
      register: broot_download_linux
      when: not is_mac

    # macOS

    - name: Install broot (macOS)
      homebrew:
        name: broot
      register: broot_download_mac
      when: is_mac

    # Common

    - name: Run post-download install
      shell: /usr/local/bin/broot --install
      when: broot_download_linux.changed or broot_download_mac.changed
