- name: Flameshot
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Install Flameshot
      become: yes
      apt:
        package: flameshot
      when: not is_mac and not is_wsl and ansible_distribution_release != 'stretch'
