- name: Remmina
  hosts: 127.0.0.1
  connection: local

  vars:
    is_debian_stretch: "{{ ansible_distribution_release == 'stretch' }}"
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Add Remmina APT package repository (Ubuntu)
      become: yes
      apt_repository:
        repo: ppa:remmina-ppa-team/remmina-next
        filename: remmina
        update_cache: no
      register: apt_repository_1
      when: is_ubuntu and not is_wsl

    - name: Add Backports repository (Debian Stretch)
      become: yes
      apt_repository:
        repo: deb http://deb.debian.org/debian stretch-backports main
        filename: backports
        update_cache: no
      register: apt_repository_2
      when: is_debian_stretch and not is_wsl

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository_1.changed or apt_repository_2.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Remmina (Debian Stretch)
      become: yes
      apt:
        package: remmina
        default_release: stretch-backports
      when: is_debian_stretch and not is_wsl

    - name: Install Remmina (other Linux)
      become: yes
      apt:
        package: remmina
      when: not is_mac and not is_debian_stretch and not is_wsl
